---
- name: Configure redundant syslog servers with VIP
  hosts: syslog
  become: yes
  vars:
    rsyslog_udp_port: 514
    rsyslog_tcp_port: 514
  pre_tasks:
    - name: Set hostname based on inventory mapping
      ansible.builtin.hostname:
        name: "{{ hostname_map[inventory_hostname] | default(inventory_hostname) }}"

  tasks:
    - name: Install rsyslog and keepalived
      ansible.builtin.package:
        name:
          - rsyslog
          - keepalived
        state: present

    - name: Ensure rsyslog enabled and started
      ansible.builtin.service:
        name: rsyslog
        state: started
        enabled: yes

    - name: Configure rsyslog to receive logs and store by sender IP
      ansible.builtin.copy:
        dest: /etc/rsyslog.d/10-listener.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          # Rsyslog listener for remote sources over UDP and TCP 514
          module(load="imudp")
          module(load="imtcp")

          # Define ruleset to write logs per sending IP under /Syslog/<IP>/syslog.log
          template(name="RemoteByIP" type="string" string="/Syslog/%fromhost-ip%/syslog.log")

          ruleset(name="remote") {
              action(type="omfile" dynaFile="RemoteByIP" createDirs="on")
          }

          # Bind inputs to the 'remote' ruleset
          input(type="imudp" port="{{ rsyslog_udp_port }}" address="0.0.0.0" ruleset="remote")
          input(type="imtcp" port="{{ rsyslog_tcp_port }}" address="0.0.0.0" ruleset="remote")

    - name: Create base directory for remote logs
      ansible.builtin.file:
        path: /Syslog
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Restart rsyslog to apply configuration
      ansible.builtin.service:
        name: rsyslog
        state: restarted

    - name: Disable host firewalls (ufw and firewalld)
      ansible.builtin.block:
        - name: Gather service facts
          ansible.builtin.service_facts:

        - name: Stop and disable firewalld if present
          ansible.builtin.service:
            name: firewalld
            enabled: no
            state: stopped
          when: "'firewalld.service' in ansible_facts.services"

        - name: Stop and disable ufw if present
          ansible.builtin.service:
            name: ufw
            enabled: no
            state: stopped
          when: "'ufw.service' in ansible_facts.services"

        - name: Ensure ufw is disabled
          ansible.builtin.command: ufw disable
          when: "'ufw.service' in ansible_facts.services"
          register: ufw_disable_cmd
          changed_when: "'disabled' in (ufw_disable_cmd.stdout | lower) or 'inactive' in (ufw_disable_cmd.stdout | lower)"
          failed_when: false

    - name: Configure keepalived
      ansible.builtin.copy:
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          vrrp_script chk_rsyslog {
              script "/usr/bin/pgrep rsyslogd"
              interval 2
              timeout 2
              fall 2
              rise 2
          }

          vrrp_instance VI_1 {
              state BACKUP
              interface {{ vip_interface }}
              virtual_router_id 51
              priority {{ 200 if inventory_hostname == '192.168.10.201' else 100 }}
              advert_int 1
              authentication {
                  auth_type PASS
                  auth_pass 42Secret!
              }
              virtual_ipaddress {
                  {{ vip_address }}/24 dev {{ vip_interface }}
              }
              track_script {
                  chk_rsyslog
              }
          }

    - name: Ensure keepalived enabled and restarted
      ansible.builtin.service:
        name: keepalived
        state: restarted
        enabled: yes
