---
- name: Configure redundant syslog servers with VIP
  hosts: syslog
  become: yes
  vars:
    rsyslog_udp_port: 514
    rsyslog_tcp_port: 514
  pre_tasks:
    - name: Set hostname based on inventory mapping
      ansible.builtin.hostname:
        name: "{{ hostname_map[inventory_hostname] | default(inventory_hostname) }}"

  tasks:
    - name: Install rsyslog
      ansible.builtin.package:
        name:
          - rsyslog
        state: present

    - name: Ensure rsyslog enabled and started
      ansible.builtin.service:
        name: rsyslog
        state: started
        enabled: yes

    - name: Configure rsyslog to receive logs and store by sender IP
      ansible.builtin.copy:
        dest: /etc/rsyslog.d/10-listener.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          # Rsyslog listener for remote sources over UDP and TCP 514
          module(load="imudp")
          module(load="imtcp")

          # Define ruleset to write logs per sending IP under /Syslog/<IP>/syslog.log
          template(name="RemoteByIP" type="string" string="/Syslog/%fromhost-ip%/syslog.log")

          ruleset(name="remote") {
              action(type="omfile" dynaFile="RemoteByIP" createDirs="on")
          }

          # Bind inputs to the 'remote' ruleset
          input(type="imudp" port="{{ rsyslog_udp_port }}" address="0.0.0.0" ruleset="remote")
          input(type="imtcp" port="{{ rsyslog_tcp_port }}" address="0.0.0.0" ruleset="remote")

    - name: Create base directory for remote logs
      ansible.builtin.file:
        path: /Syslog
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Restart rsyslog to apply configuration
      ansible.builtin.service:
        name: rsyslog
        state: restarted
        
    - name: Stop and disable ufw
      ansible.builtin.service:
        name: ufw
        enabled: no
        state: stopped
      ignore_errors: yes

    
    
    
    